# SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause

obj-$(CONFIG_RTW88_CORE)	+= rtw88_core.o
rtw88_core-y += main.o \
	   mac80211.o \
	   util.o \
	   debug.o \
	   tx.o \
	   rx.o \
	   mac.o \
	   phy.o \
	   coex.o \
	   efuse.o \
	   fw.o \
	   ps.o \
	   sec.o \
	   wow.o \
	   bf.o \
	   regd.o \
	   sar.o

obj-$(CONFIG_RTW88_8822B)	+= rtw_8822b.o
rtw_8822b-objs		:= rtw8822b.o rtw8822b_table.o

obj-$(CONFIG_RTW88_8822BE)	+= rtw_8822be.o
rtw_8822be-objs		:= rtw8822be.o

obj-$(CONFIG_RTW88_8822BU)	+= rtw_8822bu.o
rtw_8822bu-objs		:= rtw8822bu.o

obj-$(CONFIG_RTW88_8822BS)	+= rtw_8822bs.o
rtw_8822bs-objs		:= rtw8822bs.o

obj-$(CONFIG_RTW88_8822C)	+= rtw_8822c.o
rtw_8822c-objs		:= rtw8822c.o rtw8822c_table.o

obj-$(CONFIG_RTW88_8822CE)	+= rtw_8822ce.o
rtw_8822ce-objs		:= rtw8822ce.o

obj-$(CONFIG_RTW88_8822CU)	+= rtw_8822cu.o
rtw_8822cu-objs		:= rtw8822cu.o

obj-$(CONFIG_RTW88_8723X)	   += rtw_8723x.o
rtw_8723x-objs		:= rtw8723x.o

obj-$(CONFIG_RTW88_8703B)	   += rtw_8703b.o
rtw_8703b-objs		:= rtw8703b.o rtw8703b_tables.o

obj-$(CONFIG_RTW88_8822CS)	+= rtw_8822cs.o
rtw_8822cs-objs		:= rtw8822cs.o

obj-$(CONFIG_RTW88_8723CS)	    += rtw_8723cs.o
rtw_8723cs-objs		:= rtw8723cs.o

obj-$(CONFIG_RTW88_8723D)	+= rtw_8723d.o
rtw_8723d-objs		:= rtw8723d.o rtw8723d_table.o

obj-$(CONFIG_RTW88_8723DE)	+= rtw_8723de.o
rtw_8723de-objs		:= rtw8723de.o

obj-$(CONFIG_RTW88_8723DS)	+= rtw_8723ds.o
rtw_8723ds-objs		:= rtw8723ds.o

obj-$(CONFIG_RTW88_8723DU)	+= rtw_8723du.o
rtw_8723du-objs		:= rtw8723du.o

obj-$(CONFIG_RTW88_8821C)	+= rtw_8821c.o
rtw_8821c-objs		:= rtw8821c.o rtw8821c_table.o

obj-$(CONFIG_RTW88_8821CE)	+= rtw_8821ce.o
rtw_8821ce-objs		:= rtw8821ce.o

obj-$(CONFIG_RTW88_8821A)	+= rtw_8821a.o
rtw_8821a-objs		:= rtw8821a.o rtw8821a_table.o

obj-$(CONFIG_RTW88_8821AE)	+= rtw_8821ae.o
rtw_8821ae-objs		:= rtw8821ae.o

obj-$(CONFIG_RTW88_8821AU)	+= rtw_8821au.o
rtw_8821au-objs		:= rtw8821au.o

obj-$(CONFIG_RTW88_8812AU)	+= rtw_8812au.o
rtw_8812au-objs		:= rtw8812au.o

obj-$(CONFIG_RTW88_8821CS)	+= rtw_8821cs.o
rtw_8821cs-objs		:= rtw8821cs.o

obj-$(CONFIG_RTW88_8821CU)	+= rtw_8821cu.o
rtw_8821cu-objs		:= rtw8821cu.o

obj-$(CONFIG_RTW88_PCI)		+= rtw88_pci.o
rtw_pci-objs			:= pci.o

obj-$(CONFIG_RTW88_SDIO)	+= rtw88_sdio.o
rtw_sdio-objs			:= sdio.o

obj-$(CONFIG_RTW88_USB)		+= rtw88_usb.o
rtw88_usb-objs			:= usb.o
