meson-y := meson_drv.o meson_plane.o meson_crtc.o
meson-y += meson_viu.o meson_vpp.o meson_venc.o meson_vclk.o meson_canvas.o

obj-$(CONFIG_DRM_MESON) += meson.o
obj-$(CONFIG_DRM_MESON) += meson_cvbs.o
