snd-soc-meson-audio-core-objs	 := audio-core.o
snd-soc-meson-aiu-i2s-dma-objs	 := aiu-i2s-dma.o
snd-soc-meson-i2s-dai-objs	 := i2s-dai.o

obj-$(CONFIG_SND_SOC_MESON)		+= snd-soc-meson-audio-core.o
obj-$(CONFIG_SND_SOC_MESON_I2S)		+= snd-soc-meson-aiu-i2s-dma.o
obj-$(CONFIG_SND_SOC_MESON_I2S)		+= snd-soc-meson-i2s-dai.o
